### ISSUE TITLE
have 2 error code, how to fix?

### ISSUE THREAD

**Issue by ShingCK** [iKaew/hass-lifesmart-addon#12]
have 2 error code, how to fix?

Error 1:
Logger: websocket
Source: custom_components/lifesmart/__init__.py:591
Integration: LifeSmart ([documentation](https://github.com/iKaew/hass-lifesmart-addon), [issues](https://github.com/iKaew/hass-lifesmart-addon/issues))
First occurred: 上午8:13:18 (235 occurrences)
Last logged: 上午9:05:24
error from callback <function async_setup_entry.<locals>.on_message at 0x7f608c59e0>: Expecting value: line 1 column 1 (char 0)
websocket connected
error from callback <function async_setup_entry.<locals>.on_message at 0x7f7f1bf600>: 'NoneType' object has no attribute 'attributes'

Error 2:
Logger: custom_components.lifesmart
Source: custom_components/lifesmart/__init__.py:414
Integration: LifeSmart ([documentation](https://github.com/iKaew/hass-lifesmart-addon), [issues](https://github.com/iKaew/hass-lifesmart-addon/issues))
First occurred: 上午8:13:18 (133 occurrences)
Last logged: 上午9:05:14

Websocket_error: Expecting value: line 1 column 1 (char 0)
Websocket_error: 'NoneType' object has no attribute 'attributes'

**Comment by iKaew** [comment]
Can you share what kind of devices you have ?

**Comment by iKaew** [comment]
Can you also attach a full log?

**Comment by ShingCK** [comment]
> Can you share what kind of devices you have ?

I use Rpi 5,
have lifesmart Nature Mini PRO, Nature Mini PRO(POE), SPOT, CUBE Motion Sensor, CUBE Door/Window Sensor, Gas Sensor, Nature Switch

**Comment by ShingCK** [comment]
> Can you also attach a full log?

how to give you log?

**Comment by MapleEve** [comment]
2024-04-09 15:16:52.644 ERROR (Thread-2) [websocket] error from callback <function async_setup_entry.<locals>.on_message at 0x7f94bd5af7e0>: Expecting value: line 1 column 1 (char 0)
2024-04-09 15:16:52.644 ERROR (Thread-2) [custom_components.lifesmart] Websocket_error: Expecting value: line 1 column 1 (char 0)

2024-04-09 15:17:22.754 ERROR (Thread-2) [custom_components.lifesmart] Websocket_error: Expecting value: line 1 column 1 (char 0)
2024-04-09 15:17:32.756 ERROR (Thread-2) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/config/custom_components/lifesmart/__init__.py", line 539, in run
    self._ws.run_forever()
  File "/usr/local/lib/python3.12/site-packages/websocket/_app.py", line 422, in run_forever
    raise WebSocketException("socket is already opened")
websocket._exceptions.WebSocketException: socket is already opened

**Comment by MapleEve** [comment]
only 2 wss msg received
```
{
	'status': 'ok',
	'message': [{
		'ver': '0.0.0.0',
		'fullCls': 'SL_P_IR_V2',
		'me': '0001',
		'lHeart': 1712667118,
		'stat': 1,
		'data': {},
		'agt': 'XXXXX',
		'devtype': 'SL_P_IR',
		'name': 'IR',
		'agt_ver': '1.0.93p22'
	}],
	'code': 0,
	'id': 1
}

{
	"type": "io",
	"msg": {
		"fullCls": "SL_LK_YL_V1",
		"val": 8193,
		"v": 8193,
		"agt": "XXXXX",
		"devtype": "SL_LK_YL",
		"me": "61a9",
		"idx": "HISLK",
		"lsid": "XXXXX",
		"type": 95,
		"userid": "123456",
		"ts": 1712666313800
	},
	"id": 1
}
```

**Comment by iKaew** [comment]
This is fixed
